apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gdprdsar-pdfs-pvc
  namespace: production
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi